/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as LoginCallbackRouteImport } from './routes/login/callback'
import { Route as AuthenticatedOrganizationsIndexRouteImport } from './routes/_authenticated/organizations/index'
import { Route as AuthenticatedFeedbackIndexRouteImport } from './routes/_authenticated/feedback/index'
import { Route as AuthenticatedSettingsTeamRouteImport } from './routes/_authenticated/settings/team'
import { Route as AuthenticatedSettingsSystemRouteImport } from './routes/_authenticated/settings/system'
import { Route as AuthenticatedSettingsRegistrationsRouteImport } from './routes/_authenticated/settings/registrations'
import { Route as AuthenticatedSettingsPlanTemplatesRouteImport } from './routes/_authenticated/settings/plan-templates'
import { Route as AuthenticatedSettingsLicensesRouteImport } from './routes/_authenticated/settings/licenses'
import { Route as AuthenticatedSettingsLeadTypesRouteImport } from './routes/_authenticated/settings/lead-types'
import { Route as AuthenticatedSettingsDeletedLeadsRouteImport } from './routes/_authenticated/settings/deleted-leads'
import { Route as AuthenticatedSettingsCategoriesRouteImport } from './routes/_authenticated/settings/categories'
import { Route as AuthenticatedSettingsActivityLogsRouteImport } from './routes/_authenticated/settings/activity-logs'
import { Route as AuthenticatedOrganizationsOrgIdRouteImport } from './routes/_authenticated/organizations/$orgId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LoginCallbackRoute = LoginCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => LoginRoute,
} as any)
const AuthenticatedOrganizationsIndexRoute =
  AuthenticatedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFeedbackIndexRoute =
  AuthenticatedFeedbackIndexRouteImport.update({
    id: '/feedback/',
    path: '/feedback/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsTeamRoute =
  AuthenticatedSettingsTeamRouteImport.update({
    id: '/settings/team',
    path: '/settings/team',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsSystemRoute =
  AuthenticatedSettingsSystemRouteImport.update({
    id: '/settings/system',
    path: '/settings/system',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRegistrationsRoute =
  AuthenticatedSettingsRegistrationsRouteImport.update({
    id: '/settings/registrations',
    path: '/settings/registrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsPlanTemplatesRoute =
  AuthenticatedSettingsPlanTemplatesRouteImport.update({
    id: '/settings/plan-templates',
    path: '/settings/plan-templates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsLicensesRoute =
  AuthenticatedSettingsLicensesRouteImport.update({
    id: '/settings/licenses',
    path: '/settings/licenses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsLeadTypesRoute =
  AuthenticatedSettingsLeadTypesRouteImport.update({
    id: '/settings/lead-types',
    path: '/settings/lead-types',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsDeletedLeadsRoute =
  AuthenticatedSettingsDeletedLeadsRouteImport.update({
    id: '/settings/deleted-leads',
    path: '/settings/deleted-leads',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsCategoriesRoute =
  AuthenticatedSettingsCategoriesRouteImport.update({
    id: '/settings/categories',
    path: '/settings/categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsActivityLogsRoute =
  AuthenticatedSettingsActivityLogsRouteImport.update({
    id: '/settings/activity-logs',
    path: '/settings/activity-logs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdRoute =
  AuthenticatedOrganizationsOrgIdRouteImport.update({
    id: '/organizations/$orgId',
    path: '/organizations/$orgId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRouteWithChildren
  '/login/callback': typeof LoginCallbackRoute
  '/organizations/$orgId': typeof AuthenticatedOrganizationsOrgIdRoute
  '/settings/activity-logs': typeof AuthenticatedSettingsActivityLogsRoute
  '/settings/categories': typeof AuthenticatedSettingsCategoriesRoute
  '/settings/deleted-leads': typeof AuthenticatedSettingsDeletedLeadsRoute
  '/settings/lead-types': typeof AuthenticatedSettingsLeadTypesRoute
  '/settings/licenses': typeof AuthenticatedSettingsLicensesRoute
  '/settings/plan-templates': typeof AuthenticatedSettingsPlanTemplatesRoute
  '/settings/registrations': typeof AuthenticatedSettingsRegistrationsRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/feedback/': typeof AuthenticatedFeedbackIndexRoute
  '/organizations/': typeof AuthenticatedOrganizationsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRouteWithChildren
  '/login/callback': typeof LoginCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/organizations/$orgId': typeof AuthenticatedOrganizationsOrgIdRoute
  '/settings/activity-logs': typeof AuthenticatedSettingsActivityLogsRoute
  '/settings/categories': typeof AuthenticatedSettingsCategoriesRoute
  '/settings/deleted-leads': typeof AuthenticatedSettingsDeletedLeadsRoute
  '/settings/lead-types': typeof AuthenticatedSettingsLeadTypesRoute
  '/settings/licenses': typeof AuthenticatedSettingsLicensesRoute
  '/settings/plan-templates': typeof AuthenticatedSettingsPlanTemplatesRoute
  '/settings/registrations': typeof AuthenticatedSettingsRegistrationsRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/feedback': typeof AuthenticatedFeedbackIndexRoute
  '/organizations': typeof AuthenticatedOrganizationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/login/callback': typeof LoginCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/organizations/$orgId': typeof AuthenticatedOrganizationsOrgIdRoute
  '/_authenticated/settings/activity-logs': typeof AuthenticatedSettingsActivityLogsRoute
  '/_authenticated/settings/categories': typeof AuthenticatedSettingsCategoriesRoute
  '/_authenticated/settings/deleted-leads': typeof AuthenticatedSettingsDeletedLeadsRoute
  '/_authenticated/settings/lead-types': typeof AuthenticatedSettingsLeadTypesRoute
  '/_authenticated/settings/licenses': typeof AuthenticatedSettingsLicensesRoute
  '/_authenticated/settings/plan-templates': typeof AuthenticatedSettingsPlanTemplatesRoute
  '/_authenticated/settings/registrations': typeof AuthenticatedSettingsRegistrationsRoute
  '/_authenticated/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/_authenticated/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/_authenticated/feedback/': typeof AuthenticatedFeedbackIndexRoute
  '/_authenticated/organizations/': typeof AuthenticatedOrganizationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/login/callback'
    | '/organizations/$orgId'
    | '/settings/activity-logs'
    | '/settings/categories'
    | '/settings/deleted-leads'
    | '/settings/lead-types'
    | '/settings/licenses'
    | '/settings/plan-templates'
    | '/settings/registrations'
    | '/settings/system'
    | '/settings/team'
    | '/feedback/'
    | '/organizations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/login/callback'
    | '/'
    | '/organizations/$orgId'
    | '/settings/activity-logs'
    | '/settings/categories'
    | '/settings/deleted-leads'
    | '/settings/lead-types'
    | '/settings/licenses'
    | '/settings/plan-templates'
    | '/settings/registrations'
    | '/settings/system'
    | '/settings/team'
    | '/feedback'
    | '/organizations'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/login/callback'
    | '/_authenticated/'
    | '/_authenticated/organizations/$orgId'
    | '/_authenticated/settings/activity-logs'
    | '/_authenticated/settings/categories'
    | '/_authenticated/settings/deleted-leads'
    | '/_authenticated/settings/lead-types'
    | '/_authenticated/settings/licenses'
    | '/_authenticated/settings/plan-templates'
    | '/_authenticated/settings/registrations'
    | '/_authenticated/settings/system'
    | '/_authenticated/settings/team'
    | '/_authenticated/feedback/'
    | '/_authenticated/organizations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/login/callback': {
      id: '/login/callback'
      path: '/callback'
      fullPath: '/login/callback'
      preLoaderRoute: typeof LoginCallbackRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_authenticated/organizations/': {
      id: '/_authenticated/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feedback/': {
      id: '/_authenticated/feedback/'
      path: '/feedback'
      fullPath: '/feedback/'
      preLoaderRoute: typeof AuthenticatedFeedbackIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/team': {
      id: '/_authenticated/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthenticatedSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/system': {
      id: '/_authenticated/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof AuthenticatedSettingsSystemRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/registrations': {
      id: '/_authenticated/settings/registrations'
      path: '/settings/registrations'
      fullPath: '/settings/registrations'
      preLoaderRoute: typeof AuthenticatedSettingsRegistrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/plan-templates': {
      id: '/_authenticated/settings/plan-templates'
      path: '/settings/plan-templates'
      fullPath: '/settings/plan-templates'
      preLoaderRoute: typeof AuthenticatedSettingsPlanTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/licenses': {
      id: '/_authenticated/settings/licenses'
      path: '/settings/licenses'
      fullPath: '/settings/licenses'
      preLoaderRoute: typeof AuthenticatedSettingsLicensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/lead-types': {
      id: '/_authenticated/settings/lead-types'
      path: '/settings/lead-types'
      fullPath: '/settings/lead-types'
      preLoaderRoute: typeof AuthenticatedSettingsLeadTypesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/deleted-leads': {
      id: '/_authenticated/settings/deleted-leads'
      path: '/settings/deleted-leads'
      fullPath: '/settings/deleted-leads'
      preLoaderRoute: typeof AuthenticatedSettingsDeletedLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/categories': {
      id: '/_authenticated/settings/categories'
      path: '/settings/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof AuthenticatedSettingsCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/activity-logs': {
      id: '/_authenticated/settings/activity-logs'
      path: '/settings/activity-logs'
      fullPath: '/settings/activity-logs'
      preLoaderRoute: typeof AuthenticatedSettingsActivityLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizations/$orgId': {
      id: '/_authenticated/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOrganizationsOrgIdRoute: typeof AuthenticatedOrganizationsOrgIdRoute
  AuthenticatedSettingsActivityLogsRoute: typeof AuthenticatedSettingsActivityLogsRoute
  AuthenticatedSettingsCategoriesRoute: typeof AuthenticatedSettingsCategoriesRoute
  AuthenticatedSettingsDeletedLeadsRoute: typeof AuthenticatedSettingsDeletedLeadsRoute
  AuthenticatedSettingsLeadTypesRoute: typeof AuthenticatedSettingsLeadTypesRoute
  AuthenticatedSettingsLicensesRoute: typeof AuthenticatedSettingsLicensesRoute
  AuthenticatedSettingsPlanTemplatesRoute: typeof AuthenticatedSettingsPlanTemplatesRoute
  AuthenticatedSettingsRegistrationsRoute: typeof AuthenticatedSettingsRegistrationsRoute
  AuthenticatedSettingsSystemRoute: typeof AuthenticatedSettingsSystemRoute
  AuthenticatedSettingsTeamRoute: typeof AuthenticatedSettingsTeamRoute
  AuthenticatedFeedbackIndexRoute: typeof AuthenticatedFeedbackIndexRoute
  AuthenticatedOrganizationsIndexRoute: typeof AuthenticatedOrganizationsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOrganizationsOrgIdRoute: AuthenticatedOrganizationsOrgIdRoute,
  AuthenticatedSettingsActivityLogsRoute:
    AuthenticatedSettingsActivityLogsRoute,
  AuthenticatedSettingsCategoriesRoute: AuthenticatedSettingsCategoriesRoute,
  AuthenticatedSettingsDeletedLeadsRoute:
    AuthenticatedSettingsDeletedLeadsRoute,
  AuthenticatedSettingsLeadTypesRoute: AuthenticatedSettingsLeadTypesRoute,
  AuthenticatedSettingsLicensesRoute: AuthenticatedSettingsLicensesRoute,
  AuthenticatedSettingsPlanTemplatesRoute:
    AuthenticatedSettingsPlanTemplatesRoute,
  AuthenticatedSettingsRegistrationsRoute:
    AuthenticatedSettingsRegistrationsRoute,
  AuthenticatedSettingsSystemRoute: AuthenticatedSettingsSystemRoute,
  AuthenticatedSettingsTeamRoute: AuthenticatedSettingsTeamRoute,
  AuthenticatedFeedbackIndexRoute: AuthenticatedFeedbackIndexRoute,
  AuthenticatedOrganizationsIndexRoute: AuthenticatedOrganizationsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LoginRouteChildren {
  LoginCallbackRoute: typeof LoginCallbackRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginCallbackRoute: LoginCallbackRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
